import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

const sfProRounded = localFont({
  src: [
    {
      path: './../fonts/sfProRounded/sfProRounded-thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: './../fonts/sfProRounded/sfProRounded-extralight.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: './../fonts/sfProRounded/sfProRounded-light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: './../fonts/sfProRounded/sfProRounded-normal.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './../fonts/sfProRounded/sfProRounded-medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './../fonts/sfProRounded/sfProRounded-semibold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './../fonts/sfProRounded/sfProRounded-bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './../fonts/sfProRounded/sfProRounded-extrabold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: './../fonts/sfProRounded/sfProRounded-black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-sf-pro-rounded',
})

const graphik = localFont({
  src: [
    {
      path: './../fonts/graphik-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './../fonts/graphik-medium.woff2',
      weight: '500',
      style: 'normal',
    }
  ],
  display: 'swap',
  variable: '--font-graphik',
})

export const metadata = {
  title: "Happy Folks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sfProRounded.variable} ${graphik.variable}`}>{children}</body>
    </html>
  );
}
